# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 86f5ba30c67d233cced5b79c8af69fa382215c1657f90d7026075ae0763db8360a8c166d19135b30fe4957713584de00dff9f90341ed1066df1d58f7e7a2e375

test:
  secret_key_base: 5da9b59e051c2c22d2e73e5ca3984ef5714859a274dbfc4b66cac08dfcd0c4739293e94ba3b2a4a208954c03e7c8671dc97cbbc53b6a26e7df41efac410e042c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
